# Generated by Django 2.0.3 on 2018-07-02 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('image', models.FileField(upload_to='inventario_cei/static/img/items/objects')),
                ('condition', models.CharField(choices=[('d', 'Disponible'), ('p', 'En Préstamo'), ('r', 'En Reparación'), ('l', 'Perdido')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('photo', models.FileField(upload_to='inventario_cei/static/img/profile_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('state', models.CharField(choices=[('a', 'Aceptada'), ('r', 'Rechazada'), ('p', 'Pendiente')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('image', models.FileField(upload_to='inventario_cei/static/img/items/spaces')),
                ('condition', models.CharField(choices=[('d', 'Disponible'), ('p', 'En Préstamo'), ('r', 'En Reparación')], max_length=1)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario_cei.Profile')),
            ],
            bases=('inventario_cei.profile',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario_cei.Profile')),
                ('enable', models.CharField(choices=[('si', 'Habilitado'), ('no', 'No Habilitado')], max_length=2)),
            ],
            bases=('inventario_cei.profile',),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
