# Generated by Django 2.0.3 on 2018-07-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cei', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name_plural': 'Objetos'},
        ),
        migrations.AlterModelOptions(
            name='reserve',
            options={'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name_plural': 'Espacios'},
        ),
    ]
