# Generated by Django 2.0.2 on 2018-07-05 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cei', '0002_auto_20180702_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_cei.Object'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_cei.Space'),
        ),
    ]
