# Generated by Django 2.0.2 on 2018-07-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cei', '0003_auto_20180705_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
