# Generated by Django 2.0.2 on 2018-07-08 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cei', '0005_auto_20180707_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.RemoveField(
            model_name='object',
            name='description',
        ),
        migrations.RemoveField(
            model_name='object',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='object',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='space',
        ),
        migrations.RemoveField(
            model_name='space',
            name='description',
        ),
        migrations.RemoveField(
            model_name='space',
            name='name',
        ),
        migrations.AddField(
            model_name='object',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_cei.Item'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_cei.Item'),
        ),
        migrations.AddField(
            model_name='space',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_cei.Item'),
        ),
    ]
