# Generated by Django 2.0.2 on 2018-07-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cei', '0006_auto_20180708_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
